### ISSUE TITLE
How to Implement Data masking in postgresql 9.5 

### ISSUE THREAD

**Issue by unotech001** [rpobulic/pg-mask#2]
Dear Team,

We are working on postgresql 9.5 and onwards.
WE need to test and implement the data masking feature of postgresql

How it can be implement in postgresql 9.5 ???

Please help us to implement it ! Share any doc related to data masking implementation in postgresql

**Comment by rpobulic** [comment]
I developed and tested pg-mask on PostgreSQL 9.6. It was also tested on 10.0 and 10.1. I guess it will work without any issues on 9.5 also. (The current PostgreSQL version is 10.3)
The complete installation and usage instructions are in the Readme.md, clearly visible on the Github Code tab. If you have any problems with understanding or following those instructions, please be specific when asking for help, by pointing to the exact sentence you cannot follow.
